Repository hmrc/amls-art-market-participant-frontend, pull requests merged in 2019-11, with the labels that each got.

#27 Update play ui version
  project/AppDependencies.scala
Labels: Pending Review

#28 AMLS 5477 | Removed UR Banner from AMP
  app/assets/javascripts/amlsartmarketparticipantfrontend.js
  app/assets/stylesheets/amlsartmarketparticipantfrontend-app.scss
  app/views/GovukWrapper.scala.html
  release_notes/AMLS-5477.txt
Labels: Pending QA, Pending Review

#29 Align auth model with AMLS FE
  app/controllers/actions/IdentifierAction.scala
  release_notes/AMLS-5499.txt
  test/controllers/actions/IdentifierActionSpec.scala
Labels: Pending QA
