Repository hmrc/amls-art-market-participant-frontend, pull requests merged in 2019-09, with the labels that each got.

#6 Amls 5274 | Auth implementation like in frontend
  app/controllers/actions/IdentifierAction.scala
  app/models/requests/IdentifierRequest.scala
  generate-my-release-note.sh
  generate-release-notes.sh
  release_notes/AMLS-5274.txt
  test/controllers/actions/AuthActionSpec.scala
Labels: Pending QA

#5 Amls 5285 - New content for AMP journey
  app/controllers/CheckYourAnswersController.scala
  app/utils/CheckYourAnswersHelper.scala
  conf/messages.en
  test/utils/CheckYourAnswersHelperSpec.scala
  test/views/BoughtOrSoldOverThresholdViewSpec.scala
  test/views/DateTransactionOverThresholdViewSpec.scala
  test/views/IdentifyLinkedTransactionsViewSpec.scala
  test/views/IndexViewSpec.scala
  test/views/PercentageExpectedTurnoverViewSpec.scala
  test/views/SessionExpiredViewSpec.scala
  test/views/TypeOfParticipantDetailViewSpec.scala
  test/views/TypeOfParticipantViewSpec.scala
  test/views/UnauthorisedViewSpec.scala
  test/views/WhatYouNeedViewSpec.scala
Labels: Pending QA

#10 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Pending Review

#9 AMLS-5243 | Changed URLs and unit tests
  app/views/WhatYouNeedView.scala.html
  conf/app.routes
  test/utils/CheckYourAnswersHelperSpec.scala
Labels: Pending QA

#12 AMLS-5308 | Added contentSecurity localHost for up to date error page
  conf/application.conf
Labels: Pending QA, Pending Review

#19 Change the url of AMP FE to be more seamless to the user
  app/config/FrontendAppConfig.scala
  conf/prod.routes
  release_notes/AMLS-5355.txt
  test/utils/CheckYourAnswersHelperSpec.scala
Labels: Pending QA, Pending Review
